package com.droid.dolphy.hid

internal data class HidUsageAction(
    val usage: Int,
    val label: String,
)
internal val hidApplicationLaunchActions = listOf(
    HidUsageAction(0x0181, "Configuration Tool"),
    HidUsageAction(0x0182, "Programmable Button Configuration"),
    HidUsageAction(0x0183, "Consumer Control Configuration"),
    HidUsageAction(0x0184, "Word Processor"),
    HidUsageAction(0x0185, "Text Editor"),
    HidUsageAction(0x0186, "Spreadsheet"),
    HidUsageAction(0x0187, "Graphics Editor"),
    HidUsageAction(0x0188, "Presentation App"),
    HidUsageAction(0x0189, "Database App"),
    HidUsageAction(0x018A, "Email Reader"),
    HidUsageAction(0x018B, "Newsreader"),
    HidUsageAction(0x018C, "Voicemail"),
    HidUsageAction(0x018D, "Contacts/Address Book"),
    HidUsageAction(0x018E, "Calendar/Schedule"),
    HidUsageAction(0x018F, "Task/Project Manager"),
    HidUsageAction(0x0190, "Log/Journal/Timecard"),
    HidUsageAction(0x0191, "Checkbook/Finance"),
    HidUsageAction(0x0192, "Calculator"),
    HidUsageAction(0x0193, "A/V Capture/Playback"),
    HidUsageAction(0x0194, "Local Machine Browser"),
    HidUsageAction(0x0195, "LAN/WAN Browser"),
    HidUsageAction(0x0196, "Internet Browser"),
    HidUsageAction(0x0197, "Remote Networking/ISP Connect"),
    HidUsageAction(0x0198, "Network Conference"),
    HidUsageAction(0x0199, "Network Chat"),
    HidUsageAction(0x019A, "Telephony/Dialer"),
    HidUsageAction(0x019B, "Logon"),
    HidUsageAction(0x019C, "Logoff"),
    HidUsageAction(0x019D, "Logon/Logoff"),
    HidUsageAction(0x019E, "Terminal Lock/Screensaver"),
    HidUsageAction(0x019F, "Control Panel"),
    HidUsageAction(0x01A0, "Command Line Processor/Run"),
    HidUsageAction(0x01A1, "Process/Task Manager"),
    HidUsageAction(0x01A2, "Select Task/Application"),
    HidUsageAction(0x01A3, "Next Task/Application"),
    HidUsageAction(0x01A4, "Previous Task/Application"),
    HidUsageAction(0x01A5, "Preemptive Halt Task/Application"),
    HidUsageAction(0x01A6, "Integrated Help Center"),
    HidUsageAction(0x01A7, "Documents"),
    HidUsageAction(0x01A8, "Thesaurus"),
    HidUsageAction(0x01A9, "Dictionary"),
    HidUsageAction(0x01AA, "Desktop"),
    HidUsageAction(0x01AB, "Spell Check"),
    HidUsageAction(0x01AC, "Grammar Check"),
    HidUsageAction(0x01AD, "Wireless Status"),
    HidUsageAction(0x01AE, "Keyboard Layout"),
    HidUsageAction(0x01AF, "Virus Protection"),
    HidUsageAction(0x01B0, "Encryption"),
    HidUsageAction(0x01B1, "Screen Saver"),
    HidUsageAction(0x01B2, "Alarms"),
    HidUsageAction(0x01B3, "Clock"),
    HidUsageAction(0x01B4, "File Browser"),
    HidUsageAction(0x01B5, "Power Status"),
    HidUsageAction(0x01B6, "Image Browser"),
    HidUsageAction(0x01B7, "Audio Browser"),
    HidUsageAction(0x01B8, "Movie Browser"),
    HidUsageAction(0x01B9, "Digital Rights Manager"),
    HidUsageAction(0x01BA, "Digital Wallet"),
    HidUsageAction(0x01BC, "Instant Messaging"),
    HidUsageAction(0x01BD, "OEM Features/ Tips/Tutorial Browser"),
    HidUsageAction(0x01BE, "OEM Help"),
    HidUsageAction(0x01BF, "Online Community"),
    HidUsageAction(0x01C0, "Entertainment Content Browser"),
    HidUsageAction(0x01C1, "Online Shopping Browser"),
    HidUsageAction(0x01C2, "SmartCard Information/Help"),
    HidUsageAction(0x01C3, "Market Monitor/Finance Browser"),
    HidUsageAction(0x01C4, "Customized Corporate News Browser"),
    HidUsageAction(0x01C5, "Online Activity Browser"),
    HidUsageAction(0x01C6, "Research/Search Browser"),
    HidUsageAction(0x01C7, "Audio Player"),
)

internal val hidApplicationControlActions = listOf(
    HidUsageAction(0x0201, "New"),
    HidUsageAction(0x0202, "Open"),
    HidUsageAction(0x0203, "Close"),
    HidUsageAction(0x0204, "Exit"),
    HidUsageAction(0x0205, "Maximize"),
    HidUsageAction(0x0206, "Minimize"),
    HidUsageAction(0x0207, "Save"),
    HidUsageAction(0x0208, "Print"),
    HidUsageAction(0x0209, "Properties"),
    HidUsageAction(0x021A, "Undo"),
    HidUsageAction(0x021B, "Copy"),
    HidUsageAction(0x021C, "Cut"),
    HidUsageAction(0x021D, "Paste"),
    HidUsageAction(0x021E, "Select All"),
    HidUsageAction(0x021F, "Find"),
    HidUsageAction(0x0220, "Find and Replace"),
    HidUsageAction(0x0221, "Search"),
    HidUsageAction(0x0222, "Go To"),
    HidUsageAction(0x0223, "Home"),
    HidUsageAction(0x0224, "Back"),
    HidUsageAction(0x0225, "Forward"),
    HidUsageAction(0x0226, "Stop"),
    HidUsageAction(0x0227, "Refresh"),
    HidUsageAction(0x0228, "Previous Link"),
    HidUsageAction(0x0229, "Next Link"),
    HidUsageAction(0x022A, "Bookmarks"),
    HidUsageAction(0x022B, "History"),
    HidUsageAction(0x022C, "Subscriptions"),
    HidUsageAction(0x022D, "Zoom In"),
    HidUsageAction(0x022E, "Zoom Out"),
    HidUsageAction(0x022F, "Zoom"),
    HidUsageAction(0x0230, "Full Screen View"),
    HidUsageAction(0x0231, "Normal View"),
    HidUsageAction(0x0232, "View Toggle"),
    HidUsageAction(0x0233, "Scroll Up"),
    HidUsageAction(0x0234, "Scroll Down"),
    HidUsageAction(0x0235, "Scroll"),
    HidUsageAction(0x0236, "Pan Left"),
    HidUsageAction(0x0237, "Pan Right"),
    HidUsageAction(0x0238, "Pan"),
    HidUsageAction(0x0239, "New Window"),
    HidUsageAction(0x023A, "Tile Horizontally"),
    HidUsageAction(0x023B, "Tile Vertically"),
    HidUsageAction(0x023C, "Format"),
    HidUsageAction(0x023D, "Edit"),
    HidUsageAction(0x023E, "Bold"),
    HidUsageAction(0x023F, "Italics"),
    HidUsageAction(0x0240, "Underline"),
    HidUsageAction(0x0241, "Strikethrough"),
    HidUsageAction(0x0242, "Subscript"),
    HidUsageAction(0x0243, "Superscript"),
    HidUsageAction(0x0244, "All Caps"),
    HidUsageAction(0x0245, "Rotate"),
    HidUsageAction(0x0246, "Resize"),
    HidUsageAction(0x0247, "Flip horizontal"),
    HidUsageAction(0x0248, "Flip Vertical"),
    HidUsageAction(0x0249, "Mirror Horizontal"),
    HidUsageAction(0x024A, "Mirror Vertical"),
    HidUsageAction(0x024B, "Font Select"),
    HidUsageAction(0x024C, "Font Color"),
    HidUsageAction(0x024D, "Font Size"),
    HidUsageAction(0x024E, "Justify Left"),
    HidUsageAction(0x024F, "Justify Center H"),
    HidUsageAction(0x0250, "Justify Right"),
    HidUsageAction(0x0251, "Justify Block H"),
    HidUsageAction(0x0252, "Justify Top"),
    HidUsageAction(0x0253, "Justify Center V"),
    HidUsageAction(0x0254, "Justify Bottom"),
    HidUsageAction(0x0255, "Justify Block V"),
    HidUsageAction(0x0256, "Indent Decrease"),
    HidUsageAction(0x0257, "Indent Increase"),
    HidUsageAction(0x0258, "Numbered List"),
    HidUsageAction(0x0259, "Restart Numbering"),
    HidUsageAction(0x025A, "Bulleted List"),
    HidUsageAction(0x025B, "Promote"),
    HidUsageAction(0x025C, "Demote"),
    HidUsageAction(0x025D, "Yes"),
    HidUsageAction(0x025E, "No"),
    HidUsageAction(0x025F, "Cancel"),
    HidUsageAction(0x0260, "Catalog"),
    HidUsageAction(0x0261, "Buy/Checkout"),
    HidUsageAction(0x0262, "Add to Cart"),
    HidUsageAction(0x0263, "Expand"),
    HidUsageAction(0x0264, "Expand All"),
    HidUsageAction(0x0265, "Collapse"),
    HidUsageAction(0x0266, "Collapse All"),
    HidUsageAction(0x0267, "Print Preview"),
    HidUsageAction(0x0268, "Paste Special"),
    HidUsageAction(0x0269, "Insert Mode"),
    HidUsageAction(0x026A, "Delete"),
    HidUsageAction(0x026B, "Lock"),
    HidUsageAction(0x026C, "Unlock"),
    HidUsageAction(0x026D, "Protect"),
    HidUsageAction(0x026E, "Unprotect"),
    HidUsageAction(0x026F, "Attach Comment"),
    HidUsageAction(0x0270, "Delete Comment"),
    HidUsageAction(0x0271, "View Comment"),
    HidUsageAction(0x0272, "Select Word"),
    HidUsageAction(0x0273, "Select Sentence"),
    HidUsageAction(0x0274, "Select Paragraph"),
    HidUsageAction(0x0275, "Select Column"),
    HidUsageAction(0x0276, "Select Row"),
    HidUsageAction(0x0277, "Select Table"),
    HidUsageAction(0x0278, "Select Object"),
    HidUsageAction(0x0279, "Redo/Repeat"),
    HidUsageAction(0x027A, "Sort"),
    HidUsageAction(0x027B, "Sort Ascending"),
    HidUsageAction(0x027C, "Sort Descending"),
    HidUsageAction(0x027D, "Filter"),
    HidUsageAction(0x027E, "Set Clock"),
    HidUsageAction(0x027F, "View Clock"),
    HidUsageAction(0x0280, "Select Time Zone"),
    HidUsageAction(0x0281, "Edit Time Zones"),
    HidUsageAction(0x0282, "Set Alarm"),
    HidUsageAction(0x0283, "Clear Alarm"),
    HidUsageAction(0x0284, "Snooze Alarm"),
    HidUsageAction(0x0285, "Reset Alarm"),
    HidUsageAction(0x0286, "Synchronize"),
    HidUsageAction(0x0287, "Send/Receive"),
    HidUsageAction(0x0288, "Send To"),
    HidUsageAction(0x0289, "Reply"),
    HidUsageAction(0x028A, "Reply All"),
    HidUsageAction(0x028B, "Forward Msg"),
    HidUsageAction(0x028C, "Send"),
    HidUsageAction(0x028D, "Attach File"),
    HidUsageAction(0x028E, "Upload"),
    HidUsageAction(0x028F, "Download (Save Target As)"),
    HidUsageAction(0x0290, "Set Borders"),
    HidUsageAction(0x0291, "Insert Row"),
    HidUsageAction(0x0292, "Insert Column"),
    HidUsageAction(0x0293, "Insert File"),
    HidUsageAction(0x0294, "Insert Picture"),
    HidUsageAction(0x0295, "Insert Object"),
    HidUsageAction(0x0296, "Insert Symbol"),
    HidUsageAction(0x0297, "Save and Close"),
    HidUsageAction(0x0298, "Rename"),
    HidUsageAction(0x0299, "Merge"),
    HidUsageAction(0x029A, "Split"),
    HidUsageAction(0x029B, "Disribute Horizontally"),
    HidUsageAction(0x029C, "Distribute Vertically"),
)
