package com.droid.dolphy.network

import kotlinx.serialization.Serializable

@Serializable
data class RouterConfig(
    val vendor: String,
    val detectionKeyword: String,
    val defaultLogins: List<List<String>>,
    val authEndpoint: String,
    val kickEndpoint: String,
    val payloadTemplate: String,
    val method: String = "POST",
    val headers: Map<String, String> = emptyMap(),
    val rebootEndpoint: String = "",
    val infoEndpoint: String = "",
    val wifiEndpoint: String = "",
    val authType: String = "form",
    val authUsernameField: String = "user",
    val authPasswordField: String = "password",
    val authSuccessIndicator: String = "",
) {
    val allLogins: List<List<String>>
        get() = defaultLogins + FALLBACK_LOGINS.filter { it !in defaultLogins }
}

private val FALLBACK_LOGINS = listOf(
    listOf("admin", "admin"),
    listOf("admin", "1234"),
    listOf("admin", "12345"),
    listOf("admin", "123456"),
    listOf("admin", "12345678"),
    listOf("admin", "123456789"),
    listOf("admin", "password"),
    listOf("admin", "root"),
    listOf("admin", "user"),
    listOf("admin", "1111"),
    listOf("admin", "0000"),
    listOf("admin", "9876"),
    listOf("admin", "admin123"),
    listOf("admin", "admin1234"),
    listOf("admin", ""),
    listOf("root", "admin"),
    listOf("root", "root"),
    listOf("root", "12345"),
    listOf("root", "password"),
    listOf("root", ""),
    listOf("user", "user"),
    listOf("user", "1234"),
    listOf("user", "12345"),
    listOf("support", "support"),
    listOf("admin", "Passwort"),
    listOf("admin", "vodafone"),
    listOf("admin", "telecom"),
    listOf("admin", "beeline"),
    listOf("admin", "tplink"),
    listOf("admin", "tplink123"),
    listOf("admin", "archer"),
    listOf("admin", "sercomm"),
    listOf("admin", "AiCloud"),
    listOf("admin", "Asus123"),
    listOf("cisco", "cisco"),
    listOf("cisco", "password"),
    listOf("cisco", "12345"),
    listOf("ubnt", "ubnt"),
    listOf("ubnt", "password"),
    listOf("admin", "epicrouter"),
    listOf("admin", "draytek"),
    listOf("admin", "netgear1"),
    listOf("admin", "netgear123"),
    listOf("admin", "Zyxel123"),
    listOf("admin", "zyxel"),
    listOf("admin", "1234"),
    listOf("admin", "zte"),
    listOf("admin", "dlink"),
    listOf("admin", "huawei"),
    listOf("admin", "HuaweiUser"),
    listOf("admin", "me"),
    listOf("admin", "migration"),
    listOf("admin", "guest"),
    listOf("guest", "guest"),
    listOf("admin", "super"),
    listOf("admin", "supervisor"),
    listOf("admin", "admin1"),
    listOf("admin", "p@ssw0rd"),
    listOf("admin", "P@ssw0rd"),
    listOf("admin", "letmein"),
    listOf("admin", "welcome"),
)

